# Generated by Django 6.0.4 on 2026-04-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auditlog_dek_encrypted_payment_dek_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider_reference_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
