# Generated by Django 6.0.4 on 2026-04-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='secret_encrypted',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='secret_plain',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
