[pytest]

# -------------------------
# DJANGO CONFIG
# -------------------------
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = tests.py test_*.py *_tests.py

# -------------------------
# TEST DISCOVERY
# -------------------------
testpaths =
    tests/domain
    tests/application
    tests/infrastructure
    tests/interfaces

# -------------------------
# OUTPUT / DEBUGGING
# -------------------------
addopts =
    --strict-markers
    --strict-config
    --tb=short
    --disable-warnings
    -ra

# -------------------------
# CUSTOM MARKERS
# -------------------------
markers =
    domain: Pure domain tests (no Django, no DB)
    application: Use case orchestration tests
    infrastructure: DB / Redis / external integration tests
    interface: API / DRF tests
    slow: Slow tests (integration, external APIs)
    security: Security-related tests
    e2e: End-to-end tests

# -------------------------
# LOGGING CONTROL
# -------------------------
log_cli = true
log_cli_level = INFO