from abc import ABC, abstractmethod
from typing import Optional, List
import uuid

from .entities import VendorProfile, PortfolioImage, ServicePackage, Inquiry, VendorStatus


class IVendorProfileRepository(ABC):
    @abstractmethod
    def get_by_id(self, vendor_id: uuid.UUID) -> Optional[VendorProfile]: ...
    @abstractmethod
    def get_by_user_id(self, user_id: uuid.UUID) -> Optional[VendorProfile]: ...
    @abstractmethod
    def list_by_status(self, status: VendorStatus) -> List[VendorProfile]: ...
    @abstractmethod
    def save(self, profile: VendorProfile) -> VendorProfile: ...
    @abstractmethod
    def delete(self, vendor_id: uuid.UUID) -> None: ...


class IPortfolioImageRepository(ABC):
    @abstractmethod
    def get_by_id(self, image_id: uuid.UUID) -> Optional[PortfolioImage]: ...
    @abstractmethod
    def list_by_vendor(self, vendor_id: uuid.UUID) -> List[PortfolioImage]: ...
    @abstractmethod
    def save(self, image: PortfolioImage) -> PortfolioImage: ...
    @abstractmethod
    def delete(self, image_id: uuid.UUID) -> None: ...


class IServicePackageRepository(ABC):
    @abstractmethod
    def get_by_id(self, package_id: uuid.UUID) -> Optional[ServicePackage]: ...
    @abstractmethod
    def list_by_vendor(self, vendor_id: uuid.UUID) -> List[ServicePackage]: ...
    @abstractmethod
    def save(self, package: ServicePackage) -> ServicePackage: ...
    @abstractmethod
    def delete(self, package_id: uuid.UUID, deleted_by_id: Optional[uuid.UUID] = None) -> None: ...


class IInquiryRepository(ABC):
    @abstractmethod
    def get_by_id(self, inquiry_id: uuid.UUID) -> Optional[Inquiry]: ...
    @abstractmethod
    def list_by_vendor(self, vendor_id: uuid.UUID) -> List[Inquiry]: ...
    @abstractmethod
    def save(self, inquiry: Inquiry) -> Inquiry: ...
    @abstractmethod
    def delete(self, inquiry_id: uuid.UUID) -> None: ...
