# Generated by Django 5.0.6 on 2026-04-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_user_password_hash_user_groups_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
