# Generated by Django 5.1.15 on 2026-06-19 13:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_passwordresetemaildelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jti', models.CharField(db_index=True, max_length=36, unique=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=16)),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('requested_ip_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('requested_user_agent_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('used_ip_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('used_user_agent_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status', 'expires_at'], name='identity_pa_user_id_eeff72_idx'), models.Index(fields=['status', 'expires_at'], name='identity_pa_status_72916e_idx')],
            },
        ),
    ]
