# Generated by Django 5.1.15 on 2026-06-25 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_identitysession'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='identitysession',
            new_name='identity_id_user_id_273c1f_idx',
            old_name='identity_id_user_id_1c7d2b_idx',
        ),
        migrations.RenameIndex(
            model_name='identitysession',
            new_name='identity_id_user_id_07464c_idx',
            old_name='identity_id_user_id_55ef56_idx',
        ),
    ]
