# Generated by Codex on 2026-07-21

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0008_rename_identity_id_user_id_1c7d2b_idx_identity_id_user_id_273c1f_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentityDomainEventOutbox",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("event_id", models.UUIDField(unique=True)),
                ("aggregate_id", models.UUIDField(db_index=True)),
                ("aggregate_version", models.PositiveIntegerField(default=0)),
                ("event_type", models.CharField(max_length=120)),
                ("payload", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status", "next_attempt_at"], name="identity_event_status_next_idx"),
                    models.Index(fields=["aggregate_id", "aggregate_version"], name="identity_event_aggregate_idx"),
                ],
            },
        ),
    ]
