# Generated by Codex on 2026-07-23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0009_identitydomaineventoutbox"),
    ]

    operations = []
