# Generated by Codex on 2026-07-23

import secrets

from django.db import migrations, models


def _encrypt_totp_secret(secret, dek, wrapped_dek):
    from payments.domain.value_objects import EncryptedField
    from payments.helpers.encryption import encrypted_field_to_json
    from payments.infrastructure.crypto import encrypt_field

    encrypted = encrypt_field(secret.encode("utf-8"), dek)
    encrypted_with_dek = EncryptedField(
        ciphertext=encrypted.ciphertext,
        iv=encrypted.iv,
        tag=encrypted.tag,
        dek_encrypted=wrapped_dek,
    )
    return encrypted_field_to_json(encrypted_with_dek)


def encrypt_existing_totp_secrets(apps, schema_editor):
    User = apps.get_model("identity", "User")
    users = User.objects.filter(totp_secret__isnull=False).exclude(totp_secret="")
    if not users.exists():
        return

    from payments.infrastructure.vault_key_provider import VaultKeyProvider

    key_provider = VaultKeyProvider()
    for user in users.iterator():
        dek = secrets.token_bytes(32)
        wrapped_dek = key_provider.wrap_dek(dek)
        user.encrypted_totp_secret = _encrypt_totp_secret(user.totp_secret, dek, wrapped_dek)
        user.save(update_fields=["encrypted_totp_secret"])


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0010_encrypt_oauth_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="encrypted_totp_secret",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(encrypt_existing_totp_secrets, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="user",
            name="totp_secret",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="encrypted_totp_secret",
            new_name="totp_secret",
        ),
    ]
