# Generated by Django 5.1.15 on 2026-06-22 08:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventvendorassignment'),
        ('vendors', '0010_clear_portfolio_local_preview_urls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(default='Rwanda', max_length=100),
        ),
        migrations.CreateModel(
            name='EventStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_stages', to='events.event')),
                ('template_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventstagetemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventQuestionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.CharField(max_length=500)),
                ('help_text', models.TextField(blank=True)),
                ('answer_type', models.CharField(choices=[('text', 'Text'), ('boolean', 'Yes/No'), ('number', 'Number'), ('date', 'Date')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.eventstagetemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventBudgetItemTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=120)),
                ('item', models.CharField(max_length=300)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='events.eventstagetemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_tasks', to='events.event')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='events.eventstage')),
            ],
            options={
                'ordering': ['stage__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventTaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('days_before_event', models.IntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='events.eventstagetemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('travel', 'Travel'), ('corporate', 'Corporate'), ('other', 'Other')], max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'country', 'is_active'], name='events_even_event_t_dcdbc7_idx')],
            },
        ),
        migrations.AddField(
            model_name='eventstagetemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='events.eventtemplate'),
        ),
        migrations.CreateModel(
            name='EventTimelineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_timeline_items', to='events.event')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_items', to='events.eventstage')),
            ],
            options={
                'ordering': ['scheduled_at', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventVendorRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('minimum_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('maximum_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('shortlisted', 'Shortlisted'), ('booked', 'Booked')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendorprofile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_vendor_requirements', to='events.event')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_requirements', to='events.eventstage')),
            ],
            options={
                'ordering': ['stage__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventVendorRequirementTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('minimum_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('maximum_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_requirements', to='events.eventstagetemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(blank=True, max_length=100)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_activity', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', '-created_at'], name='events_even_event_i_057acd_idx'), models.Index(fields=['event', 'action'], name='events_even_event_i_125eb5_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventQuestionAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_answers', to='events.event')),
                ('question_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventquestiontemplate')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='events.eventstage')),
            ],
            options={
                'ordering': ['stage__order', 'question'],
                'indexes': [models.Index(fields=['event', 'stage'], name='events_even_event_i_cce9ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('file_url', models.URLField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_documents', to='events.event')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='events.eventstage')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'document_type'], name='events_even_event_i_e2639d_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventBudgetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=120)),
                ('item', models.CharField(max_length=300)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('quoted', 'Quoted'), ('paid', 'Paid')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_budget_items', to='events.event')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='events.eventstage')),
            ],
            options={
                'ordering': ['stage__order', 'order', 'id'],
                'indexes': [models.Index(fields=['event', 'category'], name='events_even_event_i_e6e6cf_idx'), models.Index(fields=['event', 'status'], name='events_even_event_i_7fe972_idx'), models.Index(fields=['stage', 'order'], name='events_even_stage_i_67c73e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='eventstage',
            index=models.Index(fields=['event', 'order'], name='events_even_event_i_a062fa_idx'),
        ),
        migrations.AddIndex(
            model_name='eventstage',
            index=models.Index(fields=['event', 'status'], name='events_even_event_i_73bb86_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventstage',
            constraint=models.UniqueConstraint(fields=('event', 'slug'), name='unique_event_stage_slug'),
        ),
        migrations.AddIndex(
            model_name='eventquestiontemplate',
            index=models.Index(fields=['stage', 'order'], name='events_even_stage_i_1fc35f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventbudgetitemtemplate',
            index=models.Index(fields=['stage', 'order'], name='events_even_stage_i_d33bfc_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtask',
            index=models.Index(fields=['event', 'status'], name='events_even_event_i_6ed7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtask',
            index=models.Index(fields=['event', 'due_date'], name='events_even_event_i_7d21e1_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtask',
            index=models.Index(fields=['stage', 'order'], name='events_even_stage_i_eea7fe_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtasktemplate',
            index=models.Index(fields=['stage', 'order'], name='events_even_stage_i_ad7595_idx'),
        ),
        migrations.AddIndex(
            model_name='eventstagetemplate',
            index=models.Index(fields=['template', 'order'], name='events_even_templat_01554a_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventstagetemplate',
            constraint=models.UniqueConstraint(fields=('template', 'slug'), name='unique_template_stage_slug'),
        ),
        migrations.AddIndex(
            model_name='eventtimelineitem',
            index=models.Index(fields=['event', 'scheduled_at'], name='events_even_event_i_4bbcf7_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtimelineitem',
            index=models.Index(fields=['event', 'status'], name='events_even_event_i_b4de52_idx'),
        ),
        migrations.AddIndex(
            model_name='eventvendorrequirement',
            index=models.Index(fields=['event', 'status'], name='events_even_event_i_b97156_idx'),
        ),
        migrations.AddIndex(
            model_name='eventvendorrequirement',
            index=models.Index(fields=['event', 'category'], name='events_even_event_i_272ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='eventvendorrequirement',
            index=models.Index(fields=['stage', 'order'], name='events_even_stage_i_d9297e_idx'),
        ),
        migrations.AddIndex(
            model_name='eventvendorrequirementtemplate',
            index=models.Index(fields=['stage', 'category'], name='events_even_stage_i_1667a5_idx'),
        ),
    ]
