# Generated by Django 5.1.15 on 2026-07-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0004_merge_20260702_1221'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='marketplaceprojectionoutbox',
            new_name='governance__status_549787_idx',
            old_name='governance__status_0ee9bb_idx',
        ),
        migrations.RenameIndex(
            model_name='marketplaceprojectionoutbox',
            new_name='governance__vendor__ed913f_idx',
            old_name='governance__vendor__f42562_idx',
        ),
    ]
