import base64
import json
from unittest.mock import MagicMock
import pytest
from Crypto.Cipher import DES3
from Crypto.Util.Padding import pad
from django.conf import settings
from rest_framework.test import APIClient
from django.urls import reverse

from payments.infrastructure.webhook_decryptor import FlutterwaveWebhookDecryptor

pytestmark = pytest.mark.django_db


class TestWebhookEncryption:
    @pytest.fixture
    def encryption_key(self):
        # 24-byte key for 3DES
        return b"123456789012345678901234"  # exactly 24 bytes

    @pytest.fixture
    def decryptor(self, encryption_key, settings):
        settings.FLW_ENCRYPTION_KEY = encryption_key.decode()
        return FlutterwaveWebhookDecryptor()

    def _encrypt_payload(self, payload_dict, key):
        """Encrypt payload as Flutterwave does: 3DES-CBC, Base64-encoded."""
        plaintext = json.dumps(payload_dict).encode('utf-8')
        cipher = DES3.new(key, DES3.MODE_CBC)
        iv = cipher.iv  # random IV generated by library
        encrypted = cipher.encrypt(pad(plaintext, 8))
        # Prepend IV to ciphertext
        return base64.b64encode(iv + encrypted).decode('ascii')

    def test_decrypt_valid_payload(self, decryptor, encryption_key):
        original = {"id": "evt123", "event": "charge.completed", "data": {"tx_ref": "flw_ref"}}
        encrypted = self._encrypt_payload(original, encryption_key)
        result = decryptor.decrypt(encrypted)
        assert result.success is True
        assert result.decrypted_data == original

    def test_decrypt_invalid_base64(self, decryptor):
        result = decryptor.decrypt("not_base64!!!")
        assert result.success is False

    def test_decrypt_wrong_key(self, encryption_key):
        wrong_key = b"abcdefghijklmnopabcdefgh"  # different 24-byte key
        original = {"id": "evt123"}
        # Encrypt with wrong key
        cipher = DES3.new(wrong_key, DES3.MODE_CBC)
        iv = cipher.iv
        encrypted = cipher.encrypt(pad(json.dumps(original).encode(), 8))
        encrypted_b64 = base64.b64encode(iv + encrypted).decode()

        # Use original decryptor with correct key
        decryptor = FlutterwaveWebhookDecryptor()
        decryptor.encryption_key = encryption_key  # correct key
        result = decryptor.decrypt(encrypted_b64)
        assert result.success is False

    def test_webhook_endpoint_decryption(self, client, encryption_key, settings, monkeypatch):
        settings.FLW_SECRET_HASH = "secret"
        settings.FLW_ENCRYPTION_KEY = encryption_key.decode()

        # Mock the handler to avoid real processing
        from django_app.payments import views
        monkeypatch.setattr(views, "get_command_handlers", lambda: MagicMock())

        payload = {"id": "evt_enc", "event": "charge.completed", "data": {"tx_ref": "flw_ref"}}
        encrypted_payload = self._encrypt_payload(payload, encryption_key)

        url = reverse("payments:webhook")
        response = client.post(
            url,
            data=encrypted_payload,  # raw string, not JSON
            content_type="text/plain",  # Flutterwave sends as text
            HTTP_VERIF_HASH="secret",
        )
        # Should succeed because decryption works and handler is mocked
        assert response.status_code == 200