# Generated by Django 5.1.15 on 2026-06-19 12:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_user_totp_secret_user_two_factor_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetEmailDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_hash', models.CharField(db_index=True, max_length=64)),
                ('email_domain', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('deferred', 'Deferred')], db_index=True, default='queued', max_length=16)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('provider', models.CharField(default='django_email_backend', max_length=100)),
                ('queued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_reset_email_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='identity_pa_status_6657eb_idx'), models.Index(fields=['user', 'created_at'], name='identity_pa_user_id_6427d8_idx')],
            },
        ),
    ]
