# Generated by Codex on 2026-07-23

import secrets

from django.db import migrations, models


def _encrypt_token(token, dek, wrapped_dek):
    from payments.helpers.encryption import encrypted_field_to_json
    from payments.infrastructure.crypto import encrypt_field

    encrypted = encrypt_field(token.encode("utf-8"), dek)
    encrypted_with_dek = type(encrypted)(
        ciphertext=encrypted.ciphertext,
        iv=encrypted.iv,
        tag=encrypted.tag,
        dek_encrypted=wrapped_dek,
    )
    return encrypted_field_to_json(encrypted_with_dek)


def encrypt_existing_oauth_tokens(apps, schema_editor):
    OAuthToken = apps.get_model("identity", "OAuthToken")
    tokens = OAuthToken.objects.filter(encrypted_access_token__isnull=True)
    if not tokens.exists():
        return

    from payments.infrastructure.vault_key_provider import VaultKeyProvider

    key_provider = VaultKeyProvider()
    for oauth_token in tokens.iterator():
        dek = secrets.token_bytes(32)
        wrapped_dek = key_provider.wrap_dek(dek)
        oauth_token.encrypted_access_token = _encrypt_token(oauth_token.access_token, dek, wrapped_dek)
        oauth_token.encrypted_refresh_token = (
            _encrypt_token(oauth_token.refresh_token, dek, wrapped_dek)
            if oauth_token.refresh_token
            else None
        )
        oauth_token.dek_encrypted = wrapped_dek
        oauth_token.save(
            update_fields=[
                "encrypted_access_token",
                "encrypted_refresh_token",
                "dek_encrypted",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0009_identitydomaineventoutbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauthtoken",
            name="encrypted_access_token",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="oauthtoken",
            name="encrypted_refresh_token",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oauthtoken",
            name="dek_encrypted",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.RunPython(encrypt_existing_oauth_tokens, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="oauthtoken",
            name="access_token",
        ),
        migrations.RemoveField(
            model_name="oauthtoken",
            name="refresh_token",
        ),
        migrations.AlterField(
            model_name="oauthtoken",
            name="encrypted_access_token",
            field=models.JSONField(),
        ),
    ]
