from django.urls import path
from .package_review_views import AdminVendorPackageApproveView
from .vendor_approval_views import AdminVendorApproveView
from .views import (
    FlagContentCreateView,
    AdminEmailHealthView,
    AdminMetricsView,
    AdminUserListView,
    AdminUserBanView,
    AdminUserReinstateView,
    AdminVendorListView,
    AdminVendorDetailView,
    AdminVendorRejectView,
    AdminVendorSuspendView,
    AdminVendorReinstateView,
    AdminVendorPackagePendingListView,
    AdminVendorPackageRejectView,
    AdminVendorPackageHardDeleteView,
    AdminVendorPortfolioPendingListView,
    AdminVendorPortfolioApproveView,
    AdminVendorPortfolioRejectView,
    AdminVendorPortfolioHardDeleteView,
    AdminFlagListView,
    AdminFlagResolveView,
    AdminAuditLogListView,
)

urlpatterns = [
    path("flags/", FlagContentCreateView.as_view(), name="flag-content"),
    path("metrics/", AdminMetricsView.as_view(), name="admin-metrics"),
    path("admin/health/email/", AdminEmailHealthView.as_view(), name="admin-email-health"),
    path("admin/users/", AdminUserListView.as_view(), name="admin-users"),
    path("admin/users/<uuid:user_id>/ban/", AdminUserBanView.as_view(), name="admin-user-ban"),
    path("admin/users/<uuid:user_id>/reinstate/", AdminUserReinstateView.as_view(), name="admin-user-reinstate"),
    path("admin/vendors/", AdminVendorListView.as_view(), name="admin-vendors"),
    path("admin/vendors/<uuid:vendor_id>/", AdminVendorDetailView.as_view(), name="admin-vendor-detail"),
    path("admin/vendors/<uuid:vendor_id>/approve/", AdminVendorApproveView.as_view(), name="admin-vendor-approve"),
    path("admin/vendors/<uuid:vendor_id>/reject/", AdminVendorRejectView.as_view(), name="admin-vendor-reject"),
    path("admin/vendors/<uuid:vendor_id>/suspend/", AdminVendorSuspendView.as_view(), name="admin-vendor-suspend"),
    path("admin/vendors/<uuid:vendor_id>/reinstate/", AdminVendorReinstateView.as_view(), name="admin-vendor-reinstate"),
    path("vendors/packages/pending/", AdminVendorPackagePendingListView.as_view(), name="admin-vendor-package-pending"),
    path("vendors/packages/<uuid:package_id>/approve/", AdminVendorPackageApproveView.as_view(), name="admin-vendor-package-approve"),
    path("vendors/packages/<uuid:package_id>/reject/", AdminVendorPackageRejectView.as_view(), name="admin-vendor-package-reject"),
    path("vendors/packages/<uuid:package_id>/hard-delete/", AdminVendorPackageHardDeleteView.as_view(), name="admin-vendor-package-hard-delete"),
    path("vendors/portfolio/pending/", AdminVendorPortfolioPendingListView.as_view(), name="admin-vendor-portfolio-pending"),
    path("vendors/portfolio/<uuid:media_id>/approve/", AdminVendorPortfolioApproveView.as_view(), name="admin-vendor-portfolio-approve"),
    path("vendors/portfolio/<uuid:media_id>/reject/", AdminVendorPortfolioRejectView.as_view(), name="admin-vendor-portfolio-reject"),
    path("vendors/portfolio/<uuid:media_id>/hard-delete/", AdminVendorPortfolioHardDeleteView.as_view(), name="admin-vendor-portfolio-hard-delete"),
    path("admin/flags/", AdminFlagListView.as_view(), name="admin-flags"),
    path("admin/flags/<uuid:flag_id>/resolve/", AdminFlagResolveView.as_view(), name="admin-flag-resolve"),
    path("admin/audit-logs/", AdminAuditLogListView.as_view(), name="admin-audit-logs"),
]
