# Generated by Django 6.0.4 on 2026-04-22 08:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('processed_success', 'Processed Success'), ('rejected_unknown', 'Rejected Unknown'), ('rejected_policy', 'Rejected Policy'), ('fraud_detected', 'Fraud Detected'), ('lock_failed_retry', 'Lock Failed Retry'), ('verify_failed_retry', 'Verify Failed Retry'), ('rejected_missing_ref', 'Rejected Missing Ref')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_minor', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000)])),
                ('currency', models.CharField(max_length=3)),
                ('method', models.CharField(choices=[('card', 'Card'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refund_requested', 'Refund Requested'), ('refunded', 'Refunded')], default='initiated', max_length=20)),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('context_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('environment', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], default='test', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('actor', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='payments.payment')),
            ],
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payments_pa_user_id_01767a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'expires_at'], name='payments_pa_status_04c3f6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['payment', '-created_at'], name='payments_au_payment_43e227_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='payments_au_action_343b77_idx'),
        ),
    ]
