# Generated by Django 6.0.4 on 2026-04-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='dek_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='dek_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='dek_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
