# Generated by Django 5.2 on 2026-04-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendorprofile_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='draft', max_length=20),
        ),
    ]
