# Generated by Django 5.2 on 2026-04-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendorprofile_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
