from django.urls import path
from .views import (
    EventListCreateView,
    EventDetailView,
    ChecklistListCreateView,
    ChecklistItemListCreateView,
    ChecklistItemDetailView,
    BudgetLineListCreateView,
    BudgetLineDetailView,
    GuestListCreateView,
    GuestDetailView,
    TimelineBlockListCreateView,
    TimelineBlockDetailView,
    EventVendorAssignmentListCreateView,
    EventVendorAssignmentDetailView,
    DashboardSummaryView,
)
from .workspace_views import (
    EventActivityView,
    EventBudgetItemDetailView,
    EventBudgetItemListView,
    EventDocumentDetailView,
    EventDocumentListView,
    EventQuestionAnswerDetailView,
    EventQuestionAnswerListView,
    EventStageDetailView,
    EventTaskDetailView,
    EventTaskListView,
    EventTimelineItemDetailView,
    EventTimelineItemListView,
    EventVendorRecommendationView,
    EventVendorRequirementDetailView,
    EventVendorRequirementListView,
    EventWorkspaceView,
)

urlpatterns = [
    path("", EventListCreateView.as_view(), name="event-list"),
    path("dashboard-summary/", DashboardSummaryView.as_view(), name="dashboard-summary"),
    path("<uuid:event_id>/", EventDetailView.as_view(), name="event-detail"),
    path("<uuid:event_id>/workspace/", EventWorkspaceView.as_view(), name="event-workspace"),
    path("<uuid:event_id>/workspace/stages/<uuid:stage_id>/", EventStageDetailView.as_view(), name="event-workspace-stage-detail"),
    path("<uuid:event_id>/workspace/tasks/", EventTaskListView.as_view(), name="event-workspace-tasks"),
    path("<uuid:event_id>/workspace/tasks/<uuid:object_id>/", EventTaskDetailView.as_view(), name="event-workspace-task-detail"),
    path("<uuid:event_id>/workspace/budget-items/", EventBudgetItemListView.as_view(), name="event-workspace-budget-items"),
    path("<uuid:event_id>/workspace/budget-items/<uuid:object_id>/", EventBudgetItemDetailView.as_view(), name="event-workspace-budget-item-detail"),
    path("<uuid:event_id>/workspace/vendor-requirements/", EventVendorRequirementListView.as_view(), name="event-workspace-vendor-requirements"),
    path("<uuid:event_id>/workspace/vendor-requirements/<uuid:object_id>/", EventVendorRequirementDetailView.as_view(), name="event-workspace-vendor-requirement-detail"),
    path("<uuid:event_id>/workspace/vendor-recommendations/", EventVendorRecommendationView.as_view(), name="event-workspace-vendor-recommendations"),
    path("<uuid:event_id>/workspace/questions/", EventQuestionAnswerListView.as_view(), name="event-workspace-questions"),
    path("<uuid:event_id>/workspace/questions/<uuid:object_id>/", EventQuestionAnswerDetailView.as_view(), name="event-workspace-question-detail"),
    path("<uuid:event_id>/workspace/timeline/", EventTimelineItemListView.as_view(), name="event-workspace-timeline"),
    path("<uuid:event_id>/workspace/timeline/<uuid:object_id>/", EventTimelineItemDetailView.as_view(), name="event-workspace-timeline-detail"),
    path("<uuid:event_id>/workspace/documents/", EventDocumentListView.as_view(), name="event-workspace-documents"),
    path("<uuid:event_id>/workspace/documents/<uuid:object_id>/", EventDocumentDetailView.as_view(), name="event-workspace-document-detail"),
    path("<uuid:event_id>/workspace/activity/", EventActivityView.as_view(), name="event-workspace-activity"),
    path("<uuid:event_id>/checklists/", ChecklistListCreateView.as_view(), name="event-checklists"),
    path("<uuid:event_id>/budget-lines/", BudgetLineListCreateView.as_view(), name="event-budget-lines"),
    path("<uuid:event_id>/guests/", GuestListCreateView.as_view(), name="event-guests"),
    path("<uuid:event_id>/timeline-blocks/", TimelineBlockListCreateView.as_view(), name="event-timeline-blocks"),
    path("<uuid:event_id>/vendors/", EventVendorAssignmentListCreateView.as_view(), name="event-vendors"),
    path("<uuid:event_id>/vendors/<uuid:assignment_id>/", EventVendorAssignmentDetailView.as_view(), name="event-vendor-detail"),
    path("checklists/<uuid:checklist_id>/items/", ChecklistItemListCreateView.as_view(), name="checklist-items"),
    path("checklist-items/<uuid:item_id>/", ChecklistItemDetailView.as_view(), name="checklist-item-detail"),
    path("budget-lines/<uuid:line_id>/", BudgetLineDetailView.as_view(), name="budget-line-detail"),
    path("guests/<uuid:guest_id>/", GuestDetailView.as_view(), name="guest-detail"),
    path("timeline-blocks/<uuid:block_id>/", TimelineBlockDetailView.as_view(), name="timeline-block-detail"),
]
