"""Repository interfaces for event planning."""
from abc import ABC, abstractmethod
from typing import Optional, List
import uuid

from .entities import Event, Checklist, ChecklistItem, BudgetLine, GuestEntry, TimelineBlock


class IEventRepository(ABC):
    @abstractmethod
    def get_by_id(self, event_id: uuid.UUID) -> Optional[Event]: ...
    @abstractmethod
    def list_by_planner(self, planner_id: uuid.UUID) -> List[Event]: ...
    @abstractmethod
    def save(self, event: Event) -> Event: ...
    @abstractmethod
    def delete(self, event_id: uuid.UUID) -> None: ...


class IChecklistRepository(ABC):
    @abstractmethod
    def get_by_id(self, checklist_id: uuid.UUID) -> Optional[Checklist]: ...
    @abstractmethod
    def list_by_event(self, event_id: uuid.UUID) -> List[Checklist]: ...
    @abstractmethod
    def save(self, checklist: Checklist) -> Checklist: ...
    @abstractmethod
    def delete(self, checklist_id: uuid.UUID) -> None: ...


class IChecklistItemRepository(ABC):
    @abstractmethod
    def get_by_id(self, item_id: uuid.UUID) -> Optional[ChecklistItem]: ...
    @abstractmethod
    def list_by_checklist(self, checklist_id: uuid.UUID) -> List[ChecklistItem]: ...
    @abstractmethod
    def save(self, item: ChecklistItem) -> ChecklistItem: ...
    @abstractmethod
    def delete(self, item_id: uuid.UUID) -> None: ...


class IBudgetLineRepository(ABC):
    @abstractmethod
    def get_by_id(self, line_id: uuid.UUID) -> Optional[BudgetLine]: ...
    @abstractmethod
    def list_by_event(self, event_id: uuid.UUID) -> List[BudgetLine]: ...
    @abstractmethod
    def save(self, line: BudgetLine) -> BudgetLine: ...
    @abstractmethod
    def delete(self, line_id: uuid.UUID) -> None: ...


class IGuestEntryRepository(ABC):
    @abstractmethod
    def get_by_id(self, guest_id: uuid.UUID) -> Optional[GuestEntry]: ...
    @abstractmethod
    def list_by_event(self, event_id: uuid.UUID) -> List[GuestEntry]: ...
    @abstractmethod
    def save(self, guest: GuestEntry) -> GuestEntry: ...
    @abstractmethod
    def delete(self, guest_id: uuid.UUID) -> None: ...


class ITimelineBlockRepository(ABC):
    @abstractmethod
    def get_by_id(self, block_id: uuid.UUID) -> Optional[TimelineBlock]: ...
    @abstractmethod
    def list_by_event(self, event_id: uuid.UUID) -> List[TimelineBlock]: ...
    @abstractmethod
    def save(self, block: TimelineBlock) -> TimelineBlock: ...
    @abstractmethod
    def delete(self, block_id: uuid.UUID) -> None: ...