# Generated by Django 5.2 on 2026-04-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planners', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='plannerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='plannerprofile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
