# Generated by Django 5.2 on 2026-04-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planners', '0003_plannerprofile_full_name_plannerprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannerprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
