# Generated by Django 5.1.15 on 2026-07-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_marketplace_projection_outbox'),
        ('governance', '0003_portfolio_media_audit_actions'),
    ]

    operations = [
    ]
