# Generated by Django 6.0.3 on 2026-06-09 00:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationDocument",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("business_registration", "Business Registration"),
                            ("tax_certificate", "Tax Certificate"),
                            ("trade_license", "Trade License"),
                            ("owner_id", "Owner ID"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("secure_url", models.URLField()),
                (
                    "fraud_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("review_required", "Review Required"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("fraud_score", models.PositiveSmallIntegerField(default=0)),
                ("fraud_reasons", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_documents",
                        to="vendors.vendorprofile",
                    ),
                ),
            ],
        ),
    ]
