# Generated by Django 5.1.15 on 2026-07-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_servicepackage_edit_cooldown'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='cover_image_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='cover_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='profile_image_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
