# Generated by Django 5.1.15 on 2026-07-08 08:39

import django.utils.timezone
from datetime import timedelta
import uuid
from django.conf import settings
from django.db import migrations, models


def normalize_active_portfolio_orders(apps, schema_editor):
    PortfolioImage = apps.get_model('vendors', 'PortfolioImage')
    vendor_ids = (
        PortfolioImage.objects.filter(is_active=True, is_deleted=False)
        .values_list('vendor_id', flat=True)
        .distinct()
    )
    for vendor_id in vendor_ids:
        images = list(
            PortfolioImage.objects.filter(vendor_id=vendor_id, is_active=True, is_deleted=False)
            .order_by('order', 'created_at', 'id')
            .values_list('id', flat=True)
        )
        for index, image_id in enumerate(images):
            PortfolioImage.objects.filter(id=image_id).update(order=index)


def backfill_vendor_lifecycle_contracts(apps, schema_editor):
    VendorProfile = apps.get_model('vendors', 'VendorProfile')
    ServicePackage = apps.get_model('vendors', 'ServicePackage')
    now = django.utils.timezone.now()
    VendorProfile.objects.filter(status='pending_review', submitted_at__isnull=True).update(submitted_at=now)
    VendorProfile.objects.filter(status='approved', submitted_at__isnull=True).update(submitted_at=now)
    VendorProfile.objects.filter(status='approved', approved_at__isnull=True).update(approved_at=now)
    VendorProfile.objects.filter(status='approved').update(rejected_at=None, rejection_reason=None)
    VendorProfile.objects.filter(status='rejected', rejected_at__isnull=True).update(rejected_at=now)
    ServicePackage.objects.filter(approval_status='approved', last_approved_at__isnull=True).update(last_approved_at=now)
    ServicePackage.objects.filter(
        approval_status='approved',
        next_vendor_edit_allowed_at__isnull=True,
    ).update(next_vendor_edit_allowed_at=now + timedelta(days=15))


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_servicepackage_integrity_and_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDomainEventOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(unique=True)),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('aggregate_version', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorIdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=120)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('key', models.CharField(max_length=200)),
                ('payload_fingerprint', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='inquiry',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_vendor_lifecycle_contracts, migrations.RunPython.noop),
        migrations.RunPython(normalize_active_portfolio_orders, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='portfolioimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('vendor', 'order'), name='vendors_portfolio_active_order_unique'),
        ),
        migrations.AddIndex(
            model_name='vendordomaineventoutbox',
            index=models.Index(fields=['status', 'next_attempt_at'], name='vendors_event_status_next_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordomaineventoutbox',
            index=models.Index(fields=['aggregate_id', 'aggregate_version'], name='vendors_event_aggregate_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendoridempotencyrecord',
            constraint=models.UniqueConstraint(fields=('scope', 'actor_id', 'key'), name='vendors_idempotency_scope_actor_key_unique'),
        ),
    ]
