# Generated by Django 5.1.15 on 2026-07-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0016_vendorprofileviewed'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vendorprofileviewed',
            new_name='vendorsprofileviewlogged_idx',
            old_name='vendors_profile_view_logged_idx',
        ),
    ]
